name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: NPM clean install
        run: "npm ci"

      - name: run tests
        run: "npm test"

      - name: code coverage
        run: "npm cov"
