name: side branch CI

on:
  push:
    branches:
    - '!master'
  pull_request:
    branches:
    - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2.1.0
        with:
          node-version: 12.x

      - name: NPM clean install
        run: "npm ci"

      - name: run tests
        run: "npm test"

      - name: code coverage
        run: "npm run cov"

      - name: linting
        run: "npm run lint"
